# Generated by Django 4.2 on 2026-02-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=9454115654, max_length=15),
            preserve_default=False,
        ),
    ]
