# Generated by Django 4.2 on 2026-02-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_driverrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriverRequest',
            new_name='Driver',
        ),
    ]
