# Generated by Django 4.2 on 2026-03-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='drop_address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
