# Generated by Django 4.2 on 2026-03-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0002_ride_drop_address_ride_pickup_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
